apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-prod
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/SkylarHoughtonGithub/skylab-argo-bootstrap
          revision: HEAD
          directories:
          - path: infra/*
          values:
            environment: prod
      - clusters:
          selector:
            matchLabels:
              environment: "prod"
          values:
            environment: prod
  template:
    metadata:
      name: '{{name}}-{{path.basename}}-{{values.environment}}'
      labels:
        cluster: '{{name}}'
        environment: '{{values.environment}}'
        component: infra
        service: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/SkylarHoughtonGithub/skylab-argo-bootstrap
        targetRevision: HEAD
        path: '{{path}}/{{values.environment}}'
      destination:
        server: '{{server}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true